##
## Makefile for  in /home/coudra_c/rendu/PSU_2014_zappy
## 
## Made by Coudray Colin
## Login   <coudra_c@epitech.net>
## 
## Started on  Mon May 11 08:53:16 2015 Coudray Colin
## Last update Wed Jul  1 16:50:41 2015 denche_t denche_t
##

SRC	=	zappy_ai

NAME	=	../zappy_ai

all:
	cp $(SRC) $(NAME)

clean:
	rm -f *~ */*~ */*/*~

fclean: clean
	rm -f $(NAME)

re: fclean all
